MVC _Core_Demos/MVC _Core_Demos/Models/Customer.cs
namespace MVC__Core_Demos.Models
{
    public class Customer
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }

    }
}

MVC _Core_Demos/MVC _Core_Demos/Models/ErrorViewModel.cs
namespace MVC__Core_Demos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC _Core_Demos/MVC _Core_Demos/Models/User.cs
using System.Text.Json.Serialization;

namespace MVC__Core_Demos.Models
{
    public class User
    {
        [JsonPropertyName("id")]
        public int Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("username")]
        public string UserName { get; set; }

        [JsonPropertyName("email")]
        public string Email { get; set; }

        [JsonPropertyName("address")]
        public Address Address { get; set; }
    }

    public class Address
    {
        [JsonPropertyName("street")]
        public string Street { get; set; }

        [JsonPropertyName("city")]
        public string City { get; set; }

    }
}

MVC _Core_Demos/MVC _Core_Demos/Models/ViewComponents/FirstViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC__Core_Demos.Models.ViewComponents
{
    public class FirstViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(int? id) // we need to write Invoke or InvokeAsinc method name here
        {
            //any logic to retrive data either database or from api or from anywhere
            //Customer customer = new Customer()
            List<Customer> customers= new List<Customer>() { 
            new Customer
            {
                id = 1,
                FirstName = "Datta",
                LastName = "Dawle"
            },
            new Customer()
            {
                id = 2,
                FirstName = "Prasad",
                LastName = "Dawle"
            },
              new Customer()
            {
                id = 3,
                FirstName = "Ajit",
                LastName = "Reddy"
            }
            };
            return View("First", customers.FirstOrDefault(c=>c.id==id));
        }
    }
}

MVC _Core_Demos/MVC _Core_Demos/Models/ViewComponents/UsersViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;


namespace MVC__Core_Demos.Models.ViewComponents
{
    public class UsersViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke()
        {
            // fetch all users 
            List<User> users = new List<User>();
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("https://jsonplaceholder.typicode.com/users");

            HttpResponseMessage responce = client.GetAsync("").Result;

            string json=responce.Content.ReadAsStringAsync().Result;

           users= JsonSerializer.Deserialize<List<User>>(json);

            return View("UserView",users);  
        }
    }
}

MVC _Core_Demos/MVC _Core_Demos/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using MVC__Core_Demos.Models;

namespace MVC__Core_Demos.Controllers
{
    public class CustomerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]

        public IActionResult Details()
        {
            Customer c = new Customer()
            {
                id=1,
                FirstName="Datta",
                LastName="Dawle"
            };
            return View(c);
        }
        public IActionResult Create()
        {
            //return View();
            return View("CreateNew");
        }

        [HttpGet("customer/detailsbyname/{name}")]
        //url customer/detailsbyname/datta
        public IActionResult DetailsByName(string name)
        {
            return View("DetailsByName",name);
            
        }

        // we do not use this way for dynamic partial view
        //  In mvc Core we have View Component
       /* [HttpGet]
        public PartialViewResult DynamicPartialView()
        {

            Customer c = new Customer()
            {
                id = 1,
                FirstName = "Datta",
                LastName = "Dawle"
            };
            return PartialView("_PartialView2");
        }*/

        // using view Component

    }
}

MVC _Core_Demos/MVC _Core_Demos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC__Core_Demos.Models;
using System.Diagnostics;

namespace MVC__Core_Demos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC _Core_Demos/MVC _Core_Demos/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC__Core_Demos.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
    }
}

MVC _Core_Demos/MVC _Core_Demos/Views/Home/Index.cshtml
@using MVC__Core_Demos.Taghelpers
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
<mybutton type="submit" value="Submit Button"></mybutton> |
<mybutton type="button" value="Normal Button"></mybutton>

MVC _Core_Demos/MVC _Core_Demos/Views/Product/Create.cshtml
<h1>Create new Product</h1>

MVC _Core_Demos/MVC _Core_Demos/Views/Product/Index.cshtml
<h1> Product Listing Page</h1>

<a asp-controller="Product" asp-action="Create">Create</a>

MVC _Core_Demos/MVC _Core_Demos/Views/Shared/Components/First/First.cshtml
@model MVC__Core_Demos.Models.Customer

<div>
    <h4>Partial View Component Customer Data</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MVC _Core_Demos/MVC _Core_Demos/Views/Shared/Components/Users/UserView.cshtml
@model IEnumerable<MVC__Core_Demos.Models.User>

    <h1>All Users</h1>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model=> model.Address.Street)
            </th>
            <th>
                @Html.DisplayNameFor(model=> model.Address.City)
            </th>
           
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address.Street)

            </td>
            <td>
                @Html.DisplayFor(modelItem=> item.Address.City)
            </td>
        </tr>
}
    </tbody>
</table>

MVC _Core_Demos/MVC _Core_Demos/Views/Shared/_Footer.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - MVC__Core_Demos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

MVC _Core_Demos/MVC _Core_Demos/Views/Shared/_Header.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC__Core_Demos</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

MVC _Core_Demos/MVC _Core_Demos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC__Core_Demos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC__Core_Demos.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
   <partial name="_Header"/>

    <div class="container">
        
         @if (IsSectionDefined("sidebar"))
                {
                   <div class="row">
                      <div class="col-3 border border-end-1">
                      @RenderSection("sidebar", false)
                      </div>
                    <div class="col-9">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                    </div>
                     </div>
                   
                }

         else 
         {
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
         }

    </div>

    <partial name="_Footer" />
   

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC _Core_Demos/MVC _Core_Demos/Views/Shared/_partialView.cshtml
<div class="bg-primary text-white p-5 m-3">
<h2>This is Partial View Data</h2>
</div>